# Generated by Django 5.0.3 on 2024-03-17 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='страна')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='город')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='улица')),
                ('house', models.CharField(blank=True, max_length=100, null=True, verbose_name='номер дома')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название продукта')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='модель продукта')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='дата выхода продукта на рынок')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название поставщика')),
                ('level', models.CharField(choices=[('0', 'Завод'), ('1', 'Розничная сеть'), ('2', 'Индивидуальный предприниматель')], max_length=50, verbose_name='уровень')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.contact', verbose_name='контакт')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название продавца')),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='задолженность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.contact', verbose_name='контакт')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='продукт')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.supplier', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'продавец',
                'verbose_name_plural': 'продавцы',
            },
        ),
    ]
